app/author/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from app.models import Author

class Add_Author(FlaskForm):
    full_name = StringField('Full Name', validators=[DataRequired()])
    submit = SubmitField('Add')

    def validate_full_name(self, full_name):
        author = Author.query.filter_by(full_name=full_name.data).first()
        if author:
            raise ValidationError('The author with this name alredy exists.')

app/author/routes.py
"""
    Routes to handel author object in database
    By adding, editing, deleting and displaying 
    list of all publishers from database.
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from app import  db
from app.models import Author, Book
from app.author.forms import Add_Author
from app.book.forms import Add_Book
from app.category.forms import Add_Category
from app.publisher.forms import Add_Publisher
from app.user.forms import LoginForm, RegisterForm

authors = Blueprint('authors', __name__, url_prefix='/author')

# display list of authors
@authors.route('/authors')
@login_required
def all_author():
    form_author = Add_Author()
    form_login = LoginForm()
    form_register = RegisterForm()
    authors = Author.query.all()
    return render_template('author/authors.html', authors=authors, title='Authors', form_author=form_author, form_login=form_login, form_register=form_register)

# add author to database   
@authors.route('/authors/add', methods=['POST'])
@login_required
def add_author():
    form_author = Add_Author()
    if request.method == 'POST':
        authorName = request.form['authorName'] 
        author = Author(full_name=authorName)
        db.session.add(author)
        db.session.commit()
        flash('New Author has been added!', 'success')
    elif form_author.validate_on_submit():
        flash('Error: The author alredy exists!', 'danger ')
    form = Add_Book()
    return render_template('author/author_options.html', form=form )

# edit author name
@authors.route('/authors/<int:author_id>/edit', methods=['GET','POST'])
@login_required
def edit_author(author_id):
    author = Author.query.get_or_404(author_id)
    form_author = Add_Author()
    form_login = LoginForm()
    form_register = RegisterForm()
    if form_author.validate_on_submit():
        author.full_name = form_author.full_name.data
        db.session.commit()
        flash('The author name has been updated!', 'success')
        return redirect(url_for('authors.all_author', author_id=author.AuthorId))
    elif request.method == 'GET': 
        form_author.full_name.data = author.full_name
    else:
            flash('Error: The author with this name alredy exists!', 'danger ')
    authors = Author.query.all()
    return render_template('author/authors.html', authors=authors, title='Authors', form_author=form_author, form_login=form_login, form_register=form_register)
    
# delete author from database
@authors.route('/authors/<int:author_id>/delete', methods=['GET','POST'])
@login_required
def delete_author(author_id):
    author = Author.query.get_or_404(author_id)
    db.session.delete(author)
    db.session.commit()
    flash('The author has been deleted!', 'success')
    return redirect(url_for('authors.all_author'))

# display all books from the author    
@authors.route('/author/<string:full_name>')
def author_books(full_name):
    form_login = LoginForm()
    form_register = RegisterForm()
    page = request.args.get('page', 1, type=int)
    author_query = Author.query.filter_by(full_name=full_name).first_or_404()
    books = Book.query.join(Book.author).filter(Author.full_name == author_query.full_name).order_by(Book.isbn.desc()).paginate(page=page, per_page=6)
    return render_template('author/author_books.html', books=books, author=author_query, form_login=form_login, form_register=form_register)

app/templates/author/_add_author.html
<!-- Author Modal -->
<div class="modal fade" id="authorModal" tabindex="-1" role="dialog" aria-labelledby="authorModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" id="authorModalLabel">Add Author</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="add-author-form" class="text-left border border-light p-1" method="POST" action="{{ url_for('authors.add_author') }}">
                    {{ form_author.hidden_tag() }}
                    <div class="form-group">
                        <span class="input-group-addon pb-2"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span> {{ form_author.full_name.label(class="form-control-label") }}
                        <div class="input-group">
                            {% if form_author.full_name.errors %} {{ form_author.full_name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form_author.full_name.errors %}
                                <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                            </div>
                            {% else %} {{ form_author.full_name(class="form-control mb-1") }} {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <p class="item-intro text-muted">First and last name of the author with space</p>
                    </div>
                    <div class="form-group">
                        {{ form_author.submit(class="btn btn-info btn-block") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/author/author_books.html
{% extends "base.html" %} {% block content %}
<div class="container bg-light mt-3 mb-1 pt-2 pb-1">
  <h1>The Books by <em>{{ author.full_name }}</em> <sup>{{ books.total}}</sup></h1>
 {% include "_books.html" %}
{% endblock content %}

app/templates/author/author_options.html
{{ form.author (class="browser-default custom-select mb-2")}}
<span class="input-group"><a type="button" class="badge badge-warning" data-toggle="modal" data-target="#authorModal">New Author</a></span>
{% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %} {% endif %} {% endwith %}

app/templates/author/authors.html
{% extends "base.html" %} {% block content %}
<div class="container bg-light mt-3 mb-2 pb-2">
  <div class="form-group pt-2">
    {% for author in authors %}
    <div class="pt-1">
      <a class="btn btn-info btn-sm m-1" data-toggle="modal" data-target="#edit-{{author.AuthorId}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
      <a class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#delete-{{author.AuthorId}}"><i class="fa fa-trash" aria-hidden="true"></i></a>
      <a class="article-title book-links font-weight-bold ml-3" href="{{ url_for('authors.author_books', full_name=author.full_name) }}">{{ author.full_name }}</a>
    </div>
    <!-- Edit Author Modal -->
    <div class="modal fade" id="edit-{{author.AuthorId}}" tabindex="-1" role="dialog" aria-labelledby="edit-{{author.full_name}}-Label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold" id="edit-{{author.full_name}}-Label">Edit Author</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
          </div>
          <div class="modal-body">
            <form class="text-left border border-light p-1" method="POST" action="{{ url_for('authors.edit_author',author_id=author.AuthorId) }}">
              {{ form_author.hidden_tag() }}
              <div class="form-group">
                <span class="input-group-addon"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span> {{ form_author.full_name.label(class="form-control-label") }}
                <div class="input-group">
                  {% if form_author.full_name.errors %} {{ form_author.full_name(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form_author.full_name.errors %}
                    <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                  </div>
                  {% else %} {{ form_author.full_name(class="form-control mb-1") }} {% endif %}
                </div>
                <div class="form-group">
                  <p class="item-intro text-muted">Edit the <strong>{{ author.full_name }}</strong> name</p>
                </div>
              </div>
              <div class="form-group">
                {{ form_author.submit(class="btn btn-info btn-block") }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!--End of Edit Author Modal-->
    <!-- Delete Author Modal -->
    <div class="modal fade" id="delete-{{author.AuthorId}}" tabindex="-1" role="dialog" aria-labelledby="delete-{{ author.full_name }}-Label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
          <div class="modal-header text-center">
            <h5 class="modal-title label label-default" id="Delete-{{ author.full_name }}-Label">Delete Author?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
          </div>
          <div class="modal-body">
            <h6 class="modal-title w-100 font-weight-bold">These books will be deleted as well from database.</h6>
            <ul class="list-inline">
            {% for book in author.books %}
            <hr>
            <li><img class="delete-modal-book-cover-image" src="{{ book.book_cover }}" alt="book cover image"> - {{ book.title }}</li>
            {% endfor %}
            </ul>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form  method="POST" action="{{ url_for('authors.delete_author', author_id=author.AuthorId) }}">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- End of Modal -->
    {% endfor %}
  </div>
</div>
{% endblock content %} 
{% block modals %} 
{% include "author/_add_author.html" %}
{% endblock %}