app/category/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from app.models import Category

class Add_Category(FlaskForm):
    Name = StringField('Category Name', validators=[DataRequired()])
    submit = SubmitField('Add')
    
    def validate_Name(self, Name):
        category = Category.query.filter_by(Name=Name.data).first()
        if category:
            raise ValidationError('The category alredy exists.')

app/category/routes.py
"""
    Routes to handel category object in database
    By adding, editing, deleting and displaying 
    list of all publishers from database.
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import login_required
from app import  db
from app.models import Category, Book
from app.category.forms import Add_Category
from app.book.forms import Add_Book
from app.publisher.forms import Add_Publisher
from app.author.forms import Add_Author
from app.user.forms import LoginForm, RegisterForm

categories = Blueprint('categories', __name__, url_prefix='/category')

# display list of categories
@categories.route('/categories')
@login_required
def all_categories():
    form_cat = Add_Category()
    form_login = LoginForm() 
    form_register = RegisterForm()
    categories = Category.query.all()
    return render_template('category/categories.html', categories=categories, title='Categories', form_cat=form_cat, form_login=form_login, form_register=form_register)

# add category     
@categories.route('/categories/add', methods=['POST'])
@login_required
def add_category():
    form_cat = Add_Category()
    if request.method == 'POST':
        catName = request.form['catName'] 
        category = Category(Name=catName)
        db.session.add(category)
        db.session.commit()
        flash('New category name has been added!', 'success')
    elif form_cat.validate_on_submit():
        flash('Error: The category alredy exists!', 'danger ')
    form = Add_Book()
    return render_template('category/cat_options.html', form=form )
 
# edit category name
@categories.route('/categories/<int:category_id>/edit', methods=['GET','POST'])
@login_required
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form_cat = Add_Category()
    form_login = LoginForm()
    form_register = RegisterForm()
    if form_cat.validate_on_submit():
        category.Name = form_cat.Name.data
        db.session.commit()
        flash('The category name has been updated!', 'success')
    elif request.method == 'GET': 
        form_cat.Name.data = category.Name
    else:
            flash('Error: The category alredy exists!', 'danger ')
    categories = Category.query.all()
    return render_template('category/categories.html', categories=categories, title='Categories', form_cat=form_cat, form_login=form_login, form_register=form_register)

# delete category from database
@categories.route('/categories/<int:category_id>/delete', methods=['GET','POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    flash('The category has been deleted!', 'success')
    return redirect(url_for('categories.all_categories'))
    
# display all books from the category    
@categories.route('/category/<string:Name>')
def category_books(Name):
    form_login = LoginForm()
    form_register = RegisterForm()
    page = request.args.get('page', 1, type=int)
    category_query = Category.query.filter_by(Name=Name).first_or_404()
    books = Book.query.filter_by(category=category_query).order_by(Book.isbn.desc()).paginate(page=page, per_page=6)
    return render_template('category/category_books.html',books=books, category=category_query, form_login=form_login, form_register=form_register)

app/templates/category/_add_category.html
<!-- Category Modal -->
<div class="modal fade" id="catModal" tabindex="-1" role="dialog" aria-labelledby="catModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" id="catModalLabel">Add Category</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-handler">
                    <form id="add-cat-form" class="text-left border border-light p-1" method="POST" action="{{ url_for('categories.add_category') }}">
                        {{ form_cat.hidden_tag() }}
                        <div class="form-group">
                            <span class="input-group-addon pb-2"><i class="fa fa-print" aria-hidden="true"></i></span> {{ form_cat.Name.label(class="form-control-label") }}
                            <div class="input-group">
                                {% if form_cat.Name.errors %} {{ form_cat.Name(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form_cat.Name.errors %}
                                    <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                                </div>

                                {% else %} {{ form_cat.Name(class="form-control mb-4") }} {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form_cat.submit(class="btn btn-info btn-block addCatButton") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/category/cat_options.html
{{ form.category (class="browser-default custom-select mb-2") }}
<span class="input-group"><a type="button" class="badge badge-warning" data-toggle="modal" data-target="#catModal">New Category</a></span>
{% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %} {% endif %} {% endwith %}

app/templates/category/categories.html
{% extends "base.html" %} {% block content %}
<div class="container bg-light mt-3 mb-2 pb-2">
  <div class="form-group pt-2">
    {% for category in categories %}
    <div class="pt-1">
      <a class="btn btn-info btn-sm m-1" data-toggle="modal" data-target="#catEditModal_{{category.CategoryId}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
      <a class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#catDeleteModal_{{category.CategoryId}}"><i class="fa fa-trash" aria-hidden="true"></i></a>
      <a class="article-title book-links font-weight-bold ml-3" href="{{ url_for('categories.category_books', Name=category.Name) }}">{{ category.Name }}</a>
    </div>
    <!-- Edit Category Modal -->
    <div class="modal fade" id="catEditModal_{{category.CategoryId}}" tabindex="-1" role="dialog" aria-labelledby="edit-{{ category.Name }}-Label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold" id="edit-{{ category.Name }}-Label">Edit Category</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
          </div>
          <div class="modal-body">
            <form class="text-left border border-light p-1" method="POST" action="{{ url_for('categories.edit_category', category_id=category.CategoryId) }}">
              {{ form_cat.hidden_tag() }}
              <div class="form-group">
                <span class="input-group-addon"><i class="fa fa-print" aria-hidden="true"></i></span> {{ form_cat.Name.label(class="form-control-label") }}
                <div class="input-group">
                  {% if form_cat.Name.errors %} {{ form_cat.Name(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form_cat.Name.errors %}
                    <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                  </div>
                  {% else %} {{ form_cat.Name(class="form-control mb-1") }} {% endif %}
                </div>
                <div class="form-group">
                  <p class="item-intro text-muted">Edit the <strong>{{ category.Name }}</strong> name</p>
                </div>
              </div>
              <div class="form-group">
                {{ form_cat.submit(class="btn btn-info btn-block") }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- End of Modal -->
    <!-- Delete Category Modal -->
    <div class="modal fade" id="catDeleteModal_{{category.CategoryId}}" tabindex="-1" role="dialog" aria-labelledby="delete-{{ category.Name }}-Label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
          <div class="modal-header text-center">
            <h5 class="modal-title label label-default" id="Delete-{{ category.Name }}-Label">Delete Category?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
          </div>
          <div class="modal-body">
            <h6 class="modal-title w-100 font-weight-bold">These books will be deleted as well from database.</h6>
            <ul class="list-inline">
            {% for book in category.books %}
            <hr>
            <li><img class="delete-modal-book-cover-image" src="{{ book.book_cover }}" alt="book cover image"> - {{ book.title }}</li>
            {% endfor %}
            </ul>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form  method="POST" action="{{ url_for('categories.delete_category', category_id=category.CategoryId) }}">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- End of Modal -->
    {% endfor %}
  </div>
</div>
{% endblock content %} {% block modals %} {% include "category/_add_category.html" %} {% endblock %}

app/templates/category/category_books.html
{% extends "base.html" %} {% block content %}
<div class="container bg-light mt-3 mb-1 pt-2 pb-1">
   <h1>The Category - <em>{{ category.Name }}</em> <sup>{{ books.total}}</sup></h1>
  {% include "_books.html" %}
{% endblock content %}