app/book/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from app.models import Book, Publisher, Category, Author, Lists
from wtforms_alchemy.fields import QuerySelectField
from flask_login import current_user

def choice_publisher():
    return Publisher.query.all()
    
def choice_category():
    return Category.query.all()
    
def choice_author():
    return Author.query.all()

class Add_Book(FlaskForm):
    title = StringField('Book Title', validators=[DataRequired()])
    year = StringField('Year Published', validators=[DataRequired()])
    book_cover = StringField('URL link for book cover picture', validators=[DataRequired()])
    description = TextAreaField('Book description ', validators=[DataRequired()])
    publisher = QuerySelectField(query_factory=choice_publisher, allow_blank=True,get_label='publisherName')
    category = QuerySelectField(query_factory=choice_category, allow_blank=True,get_label='Name')
    author = QuerySelectField(query_factory=choice_author, allow_blank=True,get_label='full_name')
    submit = SubmitField('Add')
    
def choice_lists():
    return Lists.query.filter_by(UserId=current_user.id).all()
    
class Add_book_to_readinglit(FlaskForm):
    lists = QuerySelectField(query_factory=choice_lists, allow_blank=True,get_label='ListName')
    submit = SubmitField('Add')

app/author/routes.py
"""
    Routes to handel author object in database
    By adding, editing, deleting and displaying 
    list of all publishers from database.
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from app import  db
from app.models import Author, Book
from app.author.forms import Add_Author
from app.book.forms import Add_Book
from app.category.forms import Add_Category
from app.publisher.forms import Add_Publisher
from app.user.forms import LoginForm, RegisterForm

authors = Blueprint('authors', __name__, url_prefix='/author')

# display list of authors
@authors.route('/authors')
@login_required
def all_author():
    form_author = Add_Author()
    form_login = LoginForm()
    form_register = RegisterForm()
    authors = Author.query.all()
    return render_template('author/authors.html', authors=authors, title='Authors', form_author=form_author, form_login=form_login, form_register=form_register)

# add author to database   
@authors.route('/authors/add', methods=['POST'])
@login_required
def add_author():
    form_author = Add_Author()
    if request.method == 'POST':
        authorName = request.form['authorName'] 
        author = Author(full_name=authorName)
        db.session.add(author)
        db.session.commit()
        flash('New Author has been added!', 'success')
    elif form_author.validate_on_submit():
        flash('Error: The author alredy exists!', 'danger ')
    form = Add_Book()
    return render_template('author/author_options.html', form=form )

# edit author name
@authors.route('/authors/<int:author_id>/edit', methods=['GET','POST'])
@login_required
def edit_author(author_id):
    author = Author.query.get_or_404(author_id)
    form_author = Add_Author()
    form_login = LoginForm()
    form_register = RegisterForm()
    if form_author.validate_on_submit():
        author.full_name = form_author.full_name.data
        db.session.commit()
        flash('The author name has been updated!', 'success')
        return redirect(url_for('authors.all_author', author_id=author.AuthorId))
    elif request.method == 'GET': 
        form_author.full_name.data = author.full_name
    else:
            flash('Error: The author with this name alredy exists!', 'danger ')
    authors = Author.query.all()
    return render_template('author/authors.html', authors=authors, title='Authors', form_author=form_author, form_login=form_login, form_register=form_register)
    
# delete author from database
@authors.route('/authors/<int:author_id>/delete', methods=['GET','POST'])
@login_required
def delete_author(author_id):
    author = Author.query.get_or_404(author_id)
    db.session.delete(author)
    db.session.commit()
    flash('The author has been deleted!', 'success')
    return redirect(url_for('authors.all_author'))

# display all books from the author    
@authors.route('/author/<string:full_name>')
def author_books(full_name):
    form_login = LoginForm()
    form_register = RegisterForm()
    page = request.args.get('page', 1, type=int)
    author_query = Author.query.filter_by(full_name=full_name).first_or_404()
    books = Book.query.join(Book.author).filter(Author.full_name == author_query.full_name).order_by(Book.isbn.desc()).paginate(page=page, per_page=6)
    return render_template('author/author_books.html', books=books, author=author_query, form_login=form_login, form_register=form_register)

app/book/routes.py
"""
    Routes to handel book object in database
    By adding, editing, deleting and displaying 
    individual book in new page from database.
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required, current_user
from app import  db
from app.models import *
from app.book.forms import Add_Book, Add_book_to_readinglit
from app.user.forms import LoginForm, RegisterForm
from app.category.forms import Add_Category
from app.publisher.forms import Add_Publisher
from app.author.forms import Add_Author
from app.reading_list.forms import Add_Readinglist

books = Blueprint('books', __name__, url_prefix='/book')

#add book    
@books.route('/book/add', methods=['GET','POST'])
@login_required
def add_book():
    form = Add_Book()
    form_login = LoginForm()
    form_register = RegisterForm()
    form_cat = Add_Category()
    form_publisher = Add_Publisher()
    form_author = Add_Author()
    author = form.author.data
    publisher = form.publisher.data
    category = form.category.data
    if form.validate_on_submit():
        book = Book(title=form.title.data, year=form.year.data, book_cover=form.book_cover.data, description=form.description.data, publisher_id=publisher.PublisherId, category_id=category.CategoryId, author_id=author.AuthorId)
        db.session.add(book)
        db.session.commit()
        flash('New Book has been added!', 'success')
        return redirect(url_for('main.index'))
    return render_template('book/add_book.html', title='New Book', form=form, legend='Add Book', form_login=form_login, form_register=form_register, form_cat=form_cat, form_publisher=form_publisher, form_author=form_author)
    
# individual book page
# add book to reading list
@books.route('/book/<int:book_isbn>', methods=['GET','POST'])
def book(book_isbn):
    form_list = Add_Readinglist()
    form_login = LoginForm()
    form_register=RegisterForm()
    book = Book.query.get_or_404(book_isbn)
    if current_user.is_authenticated:
        form = Add_book_to_readinglit()
        selected_list = form.lists.data
        if request.method == 'POST':
            book.books.append(selected_list)
            db.session.commit()
            flash('New Book has been added to list!', 'success')
            return redirect(url_for('main.index'))
        return render_template('book/book.html', title=book.title, book=book, form=form, form_list=form_list, form_login=form_login, form_register=form_register)
    return render_template('book/book.html', form_list=form_list, title=book.title, book=book, form_login=form_login, form_register=form_register)
    
# edit book information
@books.route('/book/<int:book_isbn>/edit', methods=['GET','POST'])
@login_required
def edit_book(book_isbn):
    book = Book.query.get_or_404(book_isbn)
    form = Add_Book()
    form_login = LoginForm()
    form_register = RegisterForm()
    form_cat = Add_Category()
    form_publisher = Add_Publisher()
    form_author = Add_Author()
    if form.validate_on_submit():
        book.title = form.title.data
        book.year = form.year.data
        book.book_cover = form.book_cover.data
        book.description = form.description.data
        publisher = form.publisher.data
        book.publisher_id = publisher.PublisherId
        category = form.category.data
        book.category_id = category.CategoryId
        author = form.author.data
        book.author_id = author.AuthorId
        db.session.commit()
        flash('The book detailes has been edited!', 'success')
        return redirect(url_for('books.book', book_isbn=book.isbn))
    elif request.method == 'GET':    
        form.title.data = book.title
        form.year.data = book.year
        form.book_cover.data = book.book_cover
        form.description.data = book.description
        form.publisher.data = book.publisher
        form.category.data = book.category
        form.author.data = book.author
    return render_template('book/add_book.html', title='Edit Book', form=form, legend='Edit Book', form_login=form_login, form_register=form_register, form_cat=form_cat, form_publisher=form_publisher, form_author=form_author)
    
# delete book from database
@books.route('/book/<int:book_isbn>/delete', methods=['POST'])
@login_required
def delete_book(book_isbn):
    book = Book.query.get_or_404(book_isbn)
    db.session.delete(book)
    db.session.commit()
    flash('The book has been deleted!', 'success')
    return redirect(url_for('main.index'))

app/category/routes.py
"""
    Routes to handel category object in database
    By adding, editing, deleting and displaying 
    list of all publishers from database.
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import login_required
from app import  db
from app.models import Category, Book
from app.category.forms import Add_Category
from app.book.forms import Add_Book
from app.publisher.forms import Add_Publisher
from app.author.forms import Add_Author
from app.user.forms import LoginForm, RegisterForm

categories = Blueprint('categories', __name__, url_prefix='/category')

# display list of categories
@categories.route('/categories')
@login_required
def all_categories():
    form_cat = Add_Category()
    form_login = LoginForm() 
    form_register = RegisterForm()
    categories = Category.query.all()
    return render_template('category/categories.html', categories=categories, title='Categories', form_cat=form_cat, form_login=form_login, form_register=form_register)

# add category     
@categories.route('/categories/add', methods=['POST'])
@login_required
def add_category():
    form_cat = Add_Category()
    if request.method == 'POST':
        catName = request.form['catName'] 
        category = Category(Name=catName)
        db.session.add(category)
        db.session.commit()
        flash('New category name has been added!', 'success')
    elif form_cat.validate_on_submit():
        flash('Error: The category alredy exists!', 'danger ')
    form = Add_Book()
    return render_template('category/cat_options.html', form=form )
 
# edit category name
@categories.route('/categories/<int:category_id>/edit', methods=['GET','POST'])
@login_required
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form_cat = Add_Category()
    form_login = LoginForm()
    form_register = RegisterForm()
    if form_cat.validate_on_submit():
        category.Name = form_cat.Name.data
        db.session.commit()
        flash('The category name has been updated!', 'success')
    elif request.method == 'GET': 
        form_cat.Name.data = category.Name
    else:
            flash('Error: The category alredy exists!', 'danger ')
    categories = Category.query.all()
    return render_template('category/categories.html', categories=categories, title='Categories', form_cat=form_cat, form_login=form_login, form_register=form_register)

# delete category from database
@categories.route('/categories/<int:category_id>/delete', methods=['GET','POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    flash('The category has been deleted!', 'success')
    return redirect(url_for('categories.all_categories'))
    
# display all books from the category    
@categories.route('/category/<string:Name>')
def category_books(Name):
    form_login = LoginForm()
    form_register = RegisterForm()
    page = request.args.get('page', 1, type=int)
    category_query = Category.query.filter_by(Name=Name).first_or_404()
    books = Book.query.filter_by(category=category_query).order_by(Book.isbn.desc()).paginate(page=page, per_page=6)
    return render_template('category/category_books.html',books=books, category=category_query, form_login=form_login, form_register=form_register)

app/publisher/routes.py
"""
    Routes to handel publishre object in database
    By adding, editing, deleting and displaying 
    list of all publishers from database.
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from app import  db
from app.models import Publisher, Book
from app.author.forms import Add_Author
from app.book.forms import Add_Book
from app.category.forms import Add_Category
from app.publisher.forms import Add_Publisher
from app.user.forms import LoginForm, RegisterForm

publishers = Blueprint('publishers', __name__, url_prefix='/publisher')

# display list of publishers
@publishers.route('/publisher')
@login_required
def all_publishers():
    form_publisher = Add_Publisher()
    form_login = LoginForm()
    form_register = RegisterForm()
    publishers = Publisher.query.all()
    return render_template('publisher/publishers.html', form_publisher=form_publisher, publishers=publishers, title='Publishers', form_login=form_login, form_register=form_register)

#add publisher    
@publishers.route('/publishers/add', methods=['POST'])
@login_required
def add_publisher():
    form_publisher = Add_Publisher()
    if request.method == 'POST':
        publisherName = request.form['publisherName']
        publisher = Publisher(publisherName=publisherName)
        db.session.add(publisher)
        db.session.commit()
        flash('New publisher name has been added!', 'success')
    elif form_publisher.validate_on_submit():
        flash('Error: The publisher alredy exists!', 'danger ')
    form = Add_Book()
    return render_template('publisher/publisher_options.html', form=form )
    
# edit publishers name
@publishers.route('/publisher/<int:publisher_id>/edit', methods=['GET','POST'])
@login_required
def edit_publisher(publisher_id):
    publisher = Publisher.query.get_or_404(publisher_id)
    form_publisher = Add_Publisher()
    form_login = LoginForm()
    form_register = RegisterForm()
    if form_publisher.validate_on_submit():
        publisher.publisherName = form_publisher.publisherName.data
        db.session.commit()
        flash('The publisher publisherName has been updated!', 'success')
        return redirect(url_for('publishers.all_publishers', publisher_id=publisher.PublisherId))
    elif request.method == 'GET': 
        form_publisher.publisherName.data = publisher.publisherName
    else:
            flash('Error: The publisher alredy exists!', 'danger ')
    publishers = Publisher.query.all()
    return render_template('publisher/publishers.html', form_publisher=form_publisher, publishers=publishers, title='Publishers', form_login=form_login, form_register=form_register)
    
# delete publishers from database
@publishers.route('/publisher/<int:publisher_id>/delete',  methods=['GET','POST'])
@login_required
def delete_publisher(publisher_id):
    publisher = Publisher.query.get_or_404(publisher_id)
    db.session.delete(publisher)
    db.session.commit()
    flash('The publisher has been deleted!', 'success')
    return redirect(url_for('publishers.all_publishers'))
    
# display all books from the publisher    
@publishers.route('/publisher/<string:publisherName>')
def publisher_books(publisherName):
    form_login = LoginForm()
    form_register = RegisterForm()
    page = request.args.get('page', 1, type=int)
    publisher_query = Publisher.query.filter_by(publisherName=publisherName).first_or_404()
    books = Book.query.filter_by(publisher=publisher_query).order_by(Book.isbn.desc()).paginate(page=page, per_page=6)
    return render_template('publisher/publisher_books.html',books=books, publisher=publisher_query, form_login=form_login, form_register=form_register)

app/templates/book/add_book.html
{% extends "base.html" %} {% block content %}
<div class="container bg-light mt-3 mb-2 pb-2">
    <div class="form-handler">
        <form class="text-left border border-light p-5" method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                <h2 class="mb-4 text-center">{{ legend }}</h2>
                <p class="item-intro text-muted text-center">Please add book cover full link address.</p>
                <!-- Book Title -->
                <div class="form-group">
                    <span class="input-group-addon"><i class="fa fa-book" aria-hidden="true"></i></span> {{ form.title.label(class="form-control-label font-weight-bold") }}
                    <div class="input-group">
                        {% if form.title.errors %} {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                            <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                        </div>
                        {% else %} {{ form.title(class="form-control mb-4") }} {% endif %}
                    </div>
                </div>
                <!-- Year Published -->
                <div class="form-group">
                    <span class="input-group-addon"><i class="fa fa-calendar " aria-hidden="true"></i></span> {{ form.year.label(class="form-control-label font-weight-bold") }}
                    <div class="input-group">
                        {% if form.year.errors %} {{ form.year(class="form-control form-control-lg is-invalid") }}

                        <div class="invalid-feedback">
                            {% for error in form.year.errors %}
                            <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                        </div>
                        {% else %} {{ form.year(class="form-control mb-4") }} {% endif %}
                    </div>
                </div>
                <!-- Book cover URL -->
                <div class="form-group">
                    <span class="input-group-addon"><i class="fa fa-file-image-o  " aria-hidden="true"></i></span> {{ form.book_cover.label(class="form-control-label font-weight-bold") }}
                    <div class="input-group">
                        {% if form.book_cover.errors %} {{ form.book_cover(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.book_cover.errors %}
                            <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                        </div>
                        {% else %} {{ form.book_cover(class="form-control mb-4") }} {% endif %}
                    </div>
                </div>
                <!-- Book description -->
                <div class="form-group">
                    <span class="input-group-addon"><i class="fa fa-file-text " aria-hidden="true"></i></span> {{ form.description.label(class="form-control-label font-weight-bold") }}
                    <div class="input-group">
                        {% if form.description.errors %} {{ form.description(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.description.errors %}
                            <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                        </div>
                        {% else %} {{ form.description(class="form-control mb-4") }} {% endif %}
                    </div>
                </div>
                <!-- Categories -->
                <div class="form-group">
                    <span class="input-group-addon"><i class="fa fa-archive " aria-hidden="true"></i></span> {{ form.category.label(class="form-control-label font-weight-bold") }}
                    <div class="input-group" id="option-div-1">
                        {{ form.category ( class="browser-default custom-select mb-2") }}
                        <span class="input-group"><a type="button" class="badge badge-warning" data-toggle="modal" data-target="#catModal">New Category</a></span>
                    </div>
                    <div id="errorAlert" class="alert alert-danger" role="alert" style="display:none;"></div>
                </div>
                <!-- Publishers -->
                <div class="form-group">
                    <span class="input-group-addon"><i class="fa fa-print" aria-hidden="true"></i></span> {{ form.publisher.label(class="form-control-label font-weight-bold mt-2") }}
                    <div class="input-group" id="option-div-2">
                        {{ form.publisher (class="browser-default custom-select mb-2")}}
                        <span class="input-group "><a type="button" class="badge badge-warning" data-toggle="modal" data-target="#publisherModal">New Publisher</a> </span>
                    </div>
                </div>
                <!-- Authors -->
                <div class="form-group">
                    <span class="input-group-addon"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span> {{ form.author.label(class="form-control-label font-weight-bold mt-2") }}
                    <div class="input-group" id="option-div-3">
                        {{ form.author (class="browser-default custom-select mb-2")}}
                        <span class="input-group"><a type="button" class="badge badge-warning" data-toggle="modal" data-target="#authorModal">New Author</a></span>
                    </div>

                </div>
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-info btn-block mt-4") }}
            </div>
        </form>
    </div>
</div>
{% endblock %} 
{% block modals %} 
{% include "category/_add_category.html" %} 
{% include "publisher/_add_publisher.html" %}
{% include "author/_add_author.html" %} 
{% endblock %}

app/templates/book/book.html
{% extends "base.html" %} {% block content %}
<div class="container mt-3 mb-2 pt-5 pb-2 bg-light">
  <div class="row">
    <div class="col-lg-4 mx-auto">
      <img class="img-fluid d-block mx-auto" src="{{ book.book_cover }}" alt="Book Cover"> {% if current_user.is_authenticated %}
      <div class="mt-2 ml-2">
        <form method="POST" action="" novalidate="novalidate">
          <div class="form-group">
            {{ form.lists (class='btn btn-secondary dropdown-toggle') }}
          </div>
          <div class="form-group">
            <a class="badge badge-warning" data-toggle="modal" data-target="#readinListModal">Add New List</a>
          </div>
          <div class="form-group">
            {{ form.submit(class="btn btn-info btn-block") }}
          </div>
        </form>
      </div>
      {% endif %}
    </div>
    <div class="col-lg-8 ">
      <h2 class="text-uppercase">{{ book.title }}</h2>
      <hr>
      <p class="list-inline mb-0">By author : <a class="mr-2 book-links" href="{{ url_for('authors.author_books', full_name=book.author.full_name) }}">{{ book.author.full_name }}</a> </p>
      <p class="list-inline mb-0">Publisher : <a class="mr-2 book-links" href="{{ url_for('publishers.publisher_books', publisherName=book.publisher.publisherName) }}">{{ book.publisher.publisherName }}</a></p>
      <p class="list-inline mb-0">Category : <a class="mr-2 book-links" href="{{ url_for('categories.category_books', Name=book.category.Name) }}">{{ book.category.Name }}</a>
      </p>
      <p class="list-inline ">Publication date : {{ book.year }}
      </p>
      <p class="list-inline">{{ book.description }}</p>
      {% if current_user.is_authenticated %}
      <div class="float-right">
        <a class="btn btn-info btn-sm m-1" href="{{ url_for('books.edit_book', book_isbn=book.isbn) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"><i class="fa fa-trash" aria-hidden="true"></i></button> {% endif %}
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title label label-default" id="deleteModalLabel">Delete Book?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('books.delete_book', book_isbn=book.isbn) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %} {% block modals %} {% include "reading_list/_add_readinglist.html" %} {% include "_modals_user.html" %} {% endblock %}