app/reading_list/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user
from app.models import Lists

class Add_Readinglist(FlaskForm):
    ListName = StringField('Reading List Name', validators=[DataRequired()])
    submit = SubmitField('Add')

    def validate_ListName(self, ListName):
        readinglist = Lists.query.filter_by(ListName=ListName.data).first()
        if readinglist:
            raise ValidationError(' %s alredy have this list created.'%(current_user.name))

app/main/routes.py
from flask import render_template, request, Blueprint
from app.models import Book
from app import app
from app.user.forms import LoginForm, RegisterForm

main = Blueprint('main', __name__)

# home page
@main.route('/')
@main.route('/index')
def index():
    form_login = LoginForm()
    form_register = RegisterForm()
    page = request.args.get('page', 1, type=int)
    books = Book.query.order_by(Book.isbn.desc()).paginate(page=page, per_page=6)
    return render_template('index.html',books=books, form_login=form_login, form_register=form_register )
    

    

app/reading_list/routes.py
"""
    Routes to handel reading list object in database
    By adding, editing, deleting and displaying 
    individual list with all books in the list in new page from database.
"""
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required, current_user
from app import  db
from app.models import Lists, Book
from app.reading_list.forms import Add_Readinglist
from app.user.forms import LoginForm, RegisterForm

readinglists = Blueprint('readinglists', __name__, url_prefix='/reading_list')

# list of all reading lists
@readinglists.route('/readinglist', methods=['GET','POST'])
@login_required
def all_lists():
    form_list = Add_Readinglist()
    form_login = LoginForm()
    form_register = RegisterForm()
    reading_list = Lists.query.filter_by(UserId=current_user.id).all()
    return render_template('reading_list/reading_lists.html', form_list=form_list, title=current_user.name, reading_list=reading_list, form_login=form_login, form_register=form_register)
    
# add new reading list to database
@readinglists.route('/readinglist/add', methods=['GET','POST'])
@login_required
def add_readinglist():
    form_list = Add_Readinglist()
    form_login = LoginForm()
    form_register = RegisterForm()
    if form_list.validate_on_submit():
        readinglist = Lists(ListName=form_list.ListName.data, user=current_user )
        db.session.add(readinglist)
        db.session.commit()
        flash('New reading list has been added!', 'success')
    else:
            flash('Error: %s alredy have this list created.'%(current_user.name), 'danger ')
    reading_list = Lists.query.filter_by(UserId=current_user.id).all()
    return render_template('reading_list/reading_lists.html', form_list=form_list, title=current_user.name, reading_list=reading_list, form_login=form_login, form_register=form_register)  

# individual reading list with all books in the list
@readinglists.route('/readinglist/<int:list_id>')
@login_required
def one_list(list_id):
    form_login = LoginForm()
    form_register = RegisterForm()
    reading_list = Lists.query.get_or_404(list_id)
    return render_template('reading_list/reading_list.html', title=reading_list.ListName, reading_list=reading_list, form_login=form_login, form_register=form_register)
    
# edit reading list name
@readinglists.route('/readinglist/<int:list_id>/edit', methods=['GET','POST'])
@login_required
def edit_list(list_id):
    reading_list = Lists.query.get_or_404(list_id)
    form_list = Add_Readinglist()
    form_login = LoginForm()
    form_register = RegisterForm()
    if form_list.validate_on_submit():
        reading_list.ListName = form_list.ListName.data
        db.session.commit()
        flash('The list name has been updated!', 'success')
    elif request.method == 'GET': 
        form_list.ListName.data = reading_list.ListName
    else:
            flash('Error: User or other user alredy have this list created.','danger ')
    reading_list = Lists.query.filter_by(UserId=current_user.id).all()
    return render_template('reading_list/reading_lists.html', form_list=form_list, title=current_user.name, reading_list=reading_list, form_login=form_login, form_register=form_register) 
    
# delete reading list from database
@readinglists.route('/readinglist/<int:list_id>/delete', methods=['GET','POST'])
@login_required
def delete_list(list_id):
    reading_list = Lists.query.get_or_404(list_id)
    db.session.delete(reading_list)
    db.session.commit()
    flash('The list has been deleted!', 'success')
    return redirect(url_for('readinglists.all_lists'))
    
# delete book from rading list
@readinglists.route('/readinglist/<int:list_id>/delete_book/<int:book_id>', methods=['GET','POST'])
@login_required
def delete_book_in_list(list_id, book_id):
    reading_list = Lists.query.filter_by(id=list_id).first()
    book = Book.query.filter_by(isbn=book_id).first()
    print(book.title)
    reading_list.books_in_list.remove(book)
    db.session.commit()
    flash('The book has been deleted!', 'success')
    return redirect(url_for('readinglists.one_list', list_id=list_id))

app/templates/reading_list/_add_readinglist.html
<!-- Reading List Modal -->
<div class="modal fade" id="readinListModal" tabindex="-1" role="dialog" aria-labelledby="readingListModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold" id="readingListModalLabel">Add New Reading List</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-handler">
                    <form class="text-left border border-light p-1" method="POST" action="{{ url_for('readinglists.add_readinglist') }}">
                        {{ form_list.hidden_tag() }}
                        <div class="form-group">
                            <span class="input-group-addon pb-2"><i class="fa fa-print" aria-hidden="true"></i></span> {{ form_list.ListName.label(class="form-control-label") }}
                            <div class="input-group">
                                {% if form_list.ListName.errors %} {{ form_list.ListName(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form_list.ListName.errors %}
                                    <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                                </div>
                                {% else %} {{ form_list.ListName(class="form-control mb-4") }} {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form_list.submit(class="btn btn-info btn-block") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/reading_list/reading_list.html
{% extends "base.html" %} {% block content %}
<div class="container bg-light mt-3 mb-2 pb-2">
  <div class="form-group">
    <a class="btn btn-success mt-2 btn-sm float-right" href="{{ url_for('main.index') }}"><i class="fa fa-book-medical" aria-hidden="true"></i></a>
    <a class="btn btn-danger btn-sm m-2 " href="{{ url_for('readinglists.delete_list', list_id=reading_list.id) }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
  </div>
  <div class="form-group">
      <h3 class="mb-4 pt-2 text-center"> Books : </h3>
      {% for book in reading_list.books_in_list %}
      <pre class="bg-warning"><a class="btn btn-danger mr-1 btn-sm " href="{{ url_for('readinglists.delete_book_in_list', list_id=reading_list.id, book_id=book.isbn) }}"><i class="fa fa-minus" aria-hidden="true"></i></a><a class="text-dark" href="{{ url_for('books.book', book_isbn=book.isbn) }}">{{ book.title }}</a></pre>
      {% endfor %}
  </div>
</div>
{% endblock content %}

app/templates/reading_list/reading_lists.html
{% extends "base.html" %} {% block content %}
<div class="container bg-light mt-3 mb-2 pb-2">
  <div class="form-group">
    <a class="btn btn-success mt-2 float-right" data-toggle="modal" data-target="#readinListModal"><i class="fa fa-plus" aria-hidden="true"></i>
</a>
  </div>
  <div class="form-group">
    <h2 class="mb-4 pt-4 text-center">Reading Lists</h2>
    {% for my_list in reading_list %}
    <div class="pt-1">
      <a class="btn btn-info btn-sm m-1" data-toggle="modal" data-target="#edit-{{ my_list.id }}"><i class="fa fa-pencil-square-o " aria-hidden="true"></i></a>
      <a class="article-title book-links font-weight-bold ml-3" href="{{ url_for('readinglists.one_list', list_id=my_list.id) }}">{{ my_list.ListName }}</a>
    </div>
    <!-- Edit Reading List Modal -->
    <div class="modal fade" id="edit-{{ my_list.id }}" tabindex="-1" role="dialog" aria-labelledby="edit-{{ my_list.ListName }}-Label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content bg-light">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold" id="edit-{{ my_list.ListName }}-Label">Edit Reading List</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
          </div>
          <div class="modal-body">
            <form class="text-left border border-light p-1" method="POST" action="{{ url_for('readinglists.edit_list', list_id=my_list.id) }}">
              {{ form_list.hidden_tag() }}
              <div class="form-group">
                <span class="input-group-addon"><i class="fa fa-print" aria-hidden="true"></i></span> {{ form_list.ListName.label(class="form-control-label") }}
                <div class="input-group">
                  {% if form_list.ListName.errors %} {{ form_list.ListName(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form_list.ListName.errors %}
                    <span class="text-danger">
                        {{ error }}
                        </span> {% endfor %}
                  </div>
                  {% else %} {{ form_list.ListName(class="form-control mb-1") }} {% endif %}
                </div>
                <div class="form-group">
                  <p class="item-intro text-muted">Edit the <strong>{{ my_list.ListName }}</strong> name</p>
                </div>
              </div>
              <div class="form-group">
                {{ form_list.submit(class="btn btn-info btn-block") }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- End Modal -->
    {% endfor %}
  </div>
</div>
{% endblock content %} {% block modals %} {% include "reading_list/_add_readinglist.html" %} {% endblock %}